version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-release-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
