name: Discord Notify

on:
  release:
    types: [published, edited, prereleased, released]
  push:
    tags:
      - 'v*'
      - 'release-*'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Send Release Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -c "
        import requests
        import json
        import os
        from datetime import datetime
        
        # Получение данных о релизе
        github_event_path = os.getenv('GITHUB_EVENT_PATH')
        webhook_url = os.getenv('DISCORD_WEBHOOK')
        
        if not github_event_path or not webhook_url:
            print('Не найдены необходимые переменные окружения')
            exit(1)
        
        # Чтение данных события
        with open(github_event_path, 'r', encoding='utf-8') as f:
            event_data = json.load(f)
        
        release = event_data.get('release', {})
        repository = event_data.get('repository', {})
        action = event_data.get('action', 'published')
        
        # Создание текстового сообщения
        release_name = release.get('name', 'Unnamed Release')
        release_url = release.get('html_url', '')
        release_body = release.get('body', 'Описание отсутствует')
        tag_name = release.get('tag_name', '')
        author = release.get('author', {}).get('login', 'Unknown')
        repository_name = repository.get('full_name', 'Unknown')
        
        # Статус релиза
        status_parts = []
        if release.get('prerelease', False):
            status_parts.append('Pre-release')
        if release.get('draft', False):
            status_parts.append('Draft')
        status_text = f' ({", ".join(status_parts)})' if status_parts else ''
        
        # Формирование сообщения
        message = (f\"🚀 **{release_name}**{status_text}\\n\\n\"
                 f\"{release_body}\\n\\n\"
                 f\"**📦 Tag:** {tag_name}\\n\"
                 f\"**👤 Author:** {author}\\n\"
                 f\"**🔗 Repository:** {repository_name}\\n\\n\"
                 f\"{release_url}\")
        
        # Отправка уведомления
        payload = {
            'content': message
        }
        
        try:
            response = requests.post(webhook_url, json=payload)
            response.raise_for_status()
            print('✅ Уведомление успешно отправлено в Discord')
        except Exception as e:
            print(f'❌ Ошибка при отправке уведомления: {e}')
            exit(1)
        "
